bili/urls.py
from django.contrib import admin
from django.urls import path, include
from coordinacion import views as coordinacion_views
from usuarios import views as usuarios_views
from aprendiz import views as aprendiz_views
from instructor import views as instructor_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('coordinacion.url')),
    path('', include('usuarios.url')),
    path('', include('aprendiz.url')),
    path('', include('instructor.url')),
    path('', usuarios_views.inicio_usuarios, name="inicio_usuarios"),
]

instructor/models.py
from django.db import models

# Create your models here.

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Estadoxinstru(models.Model):
    id_estadoxinstru = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=20, blank=True, null=True)
    fecha_suspe = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed =  True
        db_table = 'estadoxinstru'


class Ficha(models.Model):
    id_ficha = models.AutoField(primary_key=True)
    ficha = models.IntegerField(blank=True, null=True)
    id_programaformacion = models.ForeignKey('Programaformacion', models.DO_NOTHING, db_column='id_programaformacion', blank=True, null=True)

    class Meta:
        managed =  True
        db_table = 'ficha'


class Genero(models.Model):
    id_genero = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed =  True
        db_table = 'genero'

class Competencia(models.Model):
    id_competencia = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=250, blank=True, null=True)
    class Meta:
        managed =  True
        db_table = 'Competencia'
class Calificacion(models.Model):
    id_calificacion = models.AutoField(primary_key=True, null=False)
    nombre = models.CharField(max_length=250, blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'calificacion'

class Categoria(models.Model):
    id_categoria = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'categoria'

class Jornada(models.Model):
    id_jornada = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=80, blank=True, null=True)

    class Meta:
        managed =  True
        db_table = 'jornada'


class Mcer(models.Model):
    id_mcer = models.CharField(primary_key=True, max_length=30)
    nombre = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed =  True
        db_table = 'mcer'


class Modalidad(models.Model):
    id_modalidad = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed =  True
        db_table = 'modalidad'



class Nivelformacion(models.Model):
    id_nivel_formacion = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed =  True
        db_table = 'nivelformacion'





class Programaformacion(models.Model):
    id_programaformacion = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100, blank=True, null=True)
    id_competencia = models.ForeignKey(Competencia, models.DO_NOTHING, db_column='id_competencia', blank=True, null=True)
    id_nivel_formacion = models.ForeignKey(Nivelformacion, models.DO_NOTHING, db_column='id_nivel_formacion', blank=True, null=True)
    id_mcer = models.ForeignKey(Mcer, models.DO_NOTHING, db_column='id_mcer', blank=True, null=True)
    id_jornada = models.ForeignKey(Jornada, models.DO_NOTHING, db_column='id_jornada', blank=True, null=True)
    id_modalidad = models.ForeignKey(Modalidad, models.DO_NOTHING, db_column='id_modalidad', blank=True, null=True)

    class Meta:
        managed =  True
        db_table = 'programaformacion'


class Resultadosaprendizaje(models.Model):
    id_resultado_aprendizaje = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=150, blank=True, null=True)
    id_competencia = models.ForeignKey(Competencia, models.DO_NOTHING, db_column='id_competencia', blank=True, null=True)

    class Meta:
        managed =  True
        db_table = 'resultadosaprendizaje'


class Rol(models.Model):
    id_rol = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed =  True
        db_table = 'rol'




class Solicitud(models.Model):
    id_solicitud = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    id_tpestado = models.ForeignKey('Tpestado', models.DO_NOTHING, db_column='id_tpestado', blank=True, null=True)
    fecha_creacion = models.DateTimeField(blank=True, null=True)
    id_detallesolicitud = models.ForeignKey('Detallesolicitud', db_column='id_detallesolicitud', on_delete=models.CASCADE, blank=True, null=True)
    id_calificacion = models.ForeignKey(Calificacion, models.DO_NOTHING, db_column='id_calificacion', blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'solicitud'


class Tipodocumento(models.Model):
    id_doc = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'tipodocumento'

class TipoSolicitud(models.Model):
    id_tiposolicitud = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=250, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'TipoSolicitud'


class Detallesolicitud(models.Model):
    id_detallesolicitud = models.AutoField(primary_key=True)
    id_tiposolicitud = models.ForeignKey(TipoSolicitud, models.DO_NOTHING, db_column='id_tiposolicitud', blank=True, null=True)
    descripcion = models.CharField(max_length=250, blank=True, null=True)
    archivo = models.FileField(upload_to='archivos_soli/',blank=True, null=True)
    url = models.CharField(max_length=250, blank=True, null=True)
    imagen = models.TextField(db_column='Imagen', blank=True, null=True)  # Field name made lowercase.
    fecha_fin = models.DateTimeField(blank=True, null=True)
    fecha_inicio = models.DateTimeField(blank=True, null=True)
    id_programaformacion = models.ForeignKey(Programaformacion, models.DO_NOTHING, db_column='id_programaformacion', blank=True, null=True)
    direccion = models.CharField(max_length=250, blank=True, null=True)
    id_modalidad = models.ForeignKey(Modalidad, models.DO_NOTHING, db_column='id_modalidad', blank=True, null=True)
    id_ficha = models.ForeignKey(Ficha, models.DO_NOTHING, db_column='id_ficha', blank=True, null=True)
    id_categoria = models.ForeignKey(Categoria, models.DO_NOTHING, db_column='id_categoria', blank=True, null=True)
    id_jornada = models.ForeignKey(Jornada, models.DO_NOTHING, db_column='id_jornada', blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'detallesolicitud'
class Departamentos(models.Model):
    cod_dpto = models.IntegerField(primary_key=True)
    nombre_dpto = models.CharField(max_length=250)

    class Meta:
        managed = True
        db_table = 'departamentos'
class Municipios(models.Model):
    cod_municipio = models.IntegerField(primary_key=True)
    nombre_municipio = models.CharField(max_length=250)
    cod_dpto = models.ForeignKey(Departamentos, models.DO_NOTHING, db_column='cod_dpto', blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'municipios'
class Poblados(models.Model):
    cod_poblado = models.IntegerField(primary_key=True)
    nombre_poblado = models.CharField(max_length=250)
    cod_municipio = models.ForeignKey(Municipios, models.DO_NOTHING, db_column='cod_municipio', blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'poblados'
class Poblacion(models.Model):
    cod_poblacion = models.IntegerField(primary_key=True)
    nombre_poblacion = models.CharField(max_length=250)
    class Meta:
        managed = True
        db_table = 'poblacion'

class Tpestado(models.Model):
    id_tpestado = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'tpestado'

class UserProfile(models.Model):
    id_userprofile = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    numeroiden = models.IntegerField(unique=True, blank=True, null=True)
    id_doc = models.ForeignKey(Tipodocumento, models.DO_NOTHING, db_column='id_doc', blank=True, null=True)
    nombre = models.CharField(max_length=30, blank=True, null=True)
    id_ficha = models.ForeignKey(Ficha, models.DO_NOTHING, db_column='id_ficha', blank=True, null=True)
    nombre2 = models.CharField(max_length=30, blank=True, null=True)
    apellido = models.CharField(max_length=30, blank=True, null=True)
    apellido2 = models.CharField(max_length=30, blank=True, null=True)
    id_rol = models.ForeignKey(Rol, models.DO_NOTHING, db_column='id_rol', blank=True, null=True)
    celular = models.CharField(max_length=11, blank=True, null=True)
    correo = models.CharField(max_length=50, blank=True, null=True)
    correo1 = models.CharField(max_length=50, blank=True, null=True)
    id_genero = models.ForeignKey(Genero, models.DO_NOTHING, db_column='id_genero', blank=True, null=True)
    id_estadoxinstru = models.ForeignKey(Estadoxinstru, models.DO_NOTHING, db_column='id_estadoxinstru', blank=True, null=True)
    direccion = models.CharField(max_length=250, blank=True, null=True)
    cod_poblacion = models.ForeignKey(Poblacion, models.DO_NOTHING, db_column='cod_poblacion', blank=True, null=True)
    cod_poblado = models.ForeignKey(Poblados, models.DO_NOTHING, db_column='cod_poblado', blank=True, null=True)
    cod_municipio = models.ForeignKey(Municipios, models.DO_NOTHING, db_column='cod_municipio', blank=True, null=True)
    cod_dpto = models.ForeignKey(Departamentos, models.DO_NOTHING, db_column='cod_dpto', blank=True, null=True)
    class Meta:
        managed =  True
        db_table = 'UserProfile'

instructor/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render
from usuarios.models import Detallesolicitud
from django.core import validators


from .models import TipoSolicitud
from django.contrib.auth.models import User



class NoticiaForm(forms.ModelForm):
    class Meta:
        model = Detallesolicitud
        fields = '__all__'

instructor/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required


# Create your views here.
def inicio_instructor(request):
    return render(request, 'vistas/inicio_instructor.html',{
        'tituloventana': "Inicio"
    })

def noti_instru(request):
    noticia = Noticia.objects.all()
    return render(request, 'noti/index.html', {'noti': noticia})

def crear_instru(request):
    formulario = NoticiaForm(request.POST or None, request.FILES or None)
    if formulario.is_valid():
        formulario.save()
        return redirect('noti')
    return render(request, 'noti/crear.html', {'formulario': formulario})
def editar_instru(request, id):
    noti = Noticia.objects.get(id=id)
    formulario = NoticiaForm(request.POST or None, request.FILES or None, instance=noti) 
    if formulario.is_valid() and request.method == 'POST':
        formulario.save()
        return redirect('noti_instru') 
    return render(request, 'noti/editar.html',{'formulario':formulario } )


def eliminar_instru(request, id ):
    noti = Noticia.objects.get(id=id)
    noti.delete()
    return redirect('noti_instru')


def noticias(request):
    return render(request, 'vistas/noticias.html',{
        'tituloventana': "noticias"
    })
    

def crearsoli_instructor(request):
    user = User.objects.all()
    detallesolicitud= Detallesolicitud.objects.all()
    if request.method == 'POST':
        form_detallesolicitud = DetalleSolicitudForm(request.POST)
        if form_detallesolicitud.is_valid():
            form_detallesolicitud.save()
            return render(request,'vistas/soli.html')
    else:
        form_detallesolicitud = DetalleSolicitudForm()  # Crear una instancia del formulario correcto
    return render(request, 'vistas/soli.html', {'form_detallesolicitud': form_detallesolicitud, 'detallesolicitud': detallesolicitud, 'user': user})
def eliminartiposoli_instructor(request, id_detallesolicitud):
    detallesolicitud = Detallesolicitud.objects.get(id_detallesolicitud=id_detallesolicitud)
    detallesolicitud.delete()
    return redirect('inicio')

instructor/templates/vistas/inicio_instructor.html
{% extends "layout/layout.html" %}

{% block tituloventana %} {{tituloventana}} {% endblock  %}
{% block titulo %}INICIO{% endblock  %}
{% block content %}

<h1 class="inicio__titulo"> SECCION DE NOTICIAS Instructor</h1>

{% endblock %}

instructor/templates/vistas/noticias.html
{% extends "layout/layout.html" %}

{% block tituloventana %} {{tituloventana}} {% endblock  %}
{% block titulo %}NOTICIAS{% endblock  %}
{% block content %}
<h1 class="page__name">B-TEMA</h1>
<h2 class="page__job">Analistas y Desarrolladores SOFTWARE</h2>

{% endblock %}

instructor/templates/vistas/soli.html
{% extends "layout/layout.html" %}

{% block tituloventana %} {{tituloventana}} {% endblock  %}
{% block titulo %}Solicitud{% endblock  %}
{% block content %}
<div class="container">
  <h2>Mis SolicitudES</h2>
  <table class="table">
      <thead>
          <tr>
              <th>ID</th>
              <th>Nombre</th>
              <th>Descripción</th>
              <!-- Agrega más columnas según sea necesario -->
              <th>Acciones</th>
          </tr>
      </thead>
      <tbody>
        <a class="btn btn-primary" data-bs-toggle="modal" href="#exampleModalToggle" role="button">Crear</a>
          {% for tiposolicitud in detallesolicitud %}
          <tr>
              <td>{{ tiposolicitud.id_detallesolicitud }}</td>
              <td>{{ tiposolicitud.nombre }}</td>
              <td>{{ tiposolicitud.descripcion }}</td>
              <!-- Agrega más celdas según sea necesario -->
              <td>
                  
                  <a href="" class="btn btn-warning btn-sm">Editar</a>
                  <a href="{% url 'aprendiz:eliminar_tiposolicitud' tiposolicitud.id_detallesolicitud %}" class="btn btn-danger btn-sm">Eliminar</a>
              </td>
          </tr>
          {% endfor %}
      </tbody>
  </table>
</div>


<div class="modal_principal">
  <div class="modal fade " id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
      <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalToggleLabel">Verificacion</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                  <!-- Dentro del modal-body -->
                <form class="row g-3">
                  <!-- Campos de nombres y apellidos ya prellenados -->
                  <div class="col-md-4">
                      <label for="validationDefault01" class="form-label">Nombres</label>
                      <input type="text" class="form-control" id="validationDefault01" value="{{ user_profile.nombre }}" required>
                  </div>
                  <div class="col-md-4">
                      <label for="validationDefault02" class="form-label">Apellidos</label>
                      <input type="text" class="form-control" id="validationDefault02" value="{{ user_profile.apellido }}" required>
                  </div>
                  <!-- Otros campos del formulario -->
                  <div class="col-md-4">
                      <label for="validationDefaultUsername" class="form-label">Correo</label>
                      <input type="email" class="form-control" id="validationDefaultUsername" value="{{ user_profile.correo }}" required>
                  </div>
                  <div class="col-md-4">
                      <label for="validationDefault03" class="form-label">Número de Identificación</label>
                      <input type="text" class="form-control" id="validationDefault03" value="{{ user_profile.numeroiden }}" required>
                  </div>
                  <div class="col-md-4">
                      <label for="validationDefault04" class="form-label">Ficha</label>
                      <input type="text" class="form-control" id="validationDefault04" value="{{ user_profile.id_ficha }}" required>
                  </div>
                  <!-- Otros campos que necesites -->
                </form>

              </div>
              <div class="modal-footer">
                  <button class="btn btn-primary" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal" data-bs-dismiss="modal">Sig.</button>
              </div>
          </div>
      </div>
  </div>
</div>
</div>
<div class="modal_principal">
<div class="modal fade modal_principal" id="exampleModalToggle2" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="exampleModalToggleLabel2">Crear Solicitud</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="tipo_solicitud">
            {% comment %} <form method="post">
                {% csrf_token %}
                <select name="id_tiposolicitud" class="form-control" id="id_id_tiposolicitud">
                  <option value="">Selecciona un Tipo de Solicitud</option>
                  {% for tipo in TipoSolicitud %}
                      <option value="{{ tipo.id_tiposolicitud }}">{{ tipo.nombre }}</option>
                  {% endfor %}
              </select>
                {% comment %} {{ form_tiposolicitud.as_p }} < {% endcomment %}
                {% comment %} <button type="submit">Enviar</button> 
            </form> {% endcomment %}
        </div>
        <div class="detalle_solicitud">
            <form method="post">
                {% csrf_token %}
                {{ form_detallesolicitud.as_p }} 
                <button type="submit">Enviar</button>
            </form>
        </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary" data-bs-target="#exampleModalToggle" data-bs-toggle="modal" data-bs-dismiss="modal">Salir</button>
        </div>
      </div>
    </div>
  </div>
</div>
  

{% endblock %}